pmb3_configuration:
  wheel_model:
    description: 'Wheel model'
    choices: ['nadia', 'moog']
    default_value: 'moog'
  laser_model:
    description: 'Base laser model'
    choices: ['no-laser', 'sick-571', 'sick-561', 'sick-551', 'hokuyo']
    default_value: 'sick-571'
  camera_model:
    description: 'Base camera model'
    choices: ['realsense-d435']
    default_value: 'realsense-d435'
